### ISSUE TITLE
Builder applied to unanalyzed undesugared AST instead of analyzed desugared AST

### ISSUE THREAD

**Issue by mvandertuin** [TUDelft-IN4303-2014/assignments#31]
Although (source) is not present at the MiniJava-Menus.esv file (as stated in https://github.com/TUDelft-IN4303/assignments/blob/master/milestone3-codegen/questions.md), the builder is still applied to the unanalysed, undesugared AST instead of the correct one.

What could be possible other options to fix this issue?

**Comment by Virtlink** [comment]
The signature of a builder is generally:

```
generate-jbc: (selected, position, ast, path, project-path) -> (filename, result)
```

Be sure to use the `ast` variable, not the `selected` variable.

**Comment by mvandertuin** [comment]
Thanks. Now I use the ast variable:

```
generate-jbc: (selected, position, ast, path, project-path) -> (filename, result)
        where
            filename := <guarantee-extension(|"j.aterm")> path
            ; result := <program-to-jbc> (ast,path)
```

However, when trying to use the reference to the classname I got the following generated Jasmin AST:

```
"Main"{ Def(
                           URI(
                             Language("MiniJava")
                           , [ID(NablNsClass(), "Main", Unique("/ExampleCode/MiniJava/MainClass.mjv/0")), Anonymous("/ExampleCode/MiniJava/MainClass.mjv/0")]
                           )
                         )
                       })
```

Which ís the analyzed syntax, but I would think you would like to have the desugared syntax?

**Comment by trensen** [comment]
You can obtain the desugared AST using the `desugar-all` strategy:
`... := <desugar-all> ast`

Make sure that `common/desugar` is imported as well!

**Comment by Gohla** [comment]
Why do you want the desugared AST but not the analyzed one?

**Comment by trensen** [comment]
Should the `ast` in `generate-jbc: (selected, position, ast, path, project-path)` already be the analysed one?
In my case it isn't: nodes are still like `Add(..., ...)` instead of `BinExp(Plus(), ..., ...)`.
The strange thing is that this only happens in `generate-jbc`: in the `Generate Java class files` and `Run Java class files` rules the `ast` is already in the proper format.

**Comment by trensen** [comment]
YES, I finally understand why this "strange" behaviour happened! I think more people are struggling with an unanalysed and not-desugared ASTs due to the same reason:
In `MiniJava/editor/MiniJava-Menus.esv` a menu `Generate` had to be added in `assignment10`. However, I associated an annotation `(source)` with action `Generate Java Bytecode`. `(source)` means that "Spoofax must run the builder on an unanalysed (and also not desugared) AST." (see: https://github.com/TUDelft-IN4303/assignments/blob/master/milestone1-editor/day4.md)
After removing this annotation, everything is working perfectly :+1:

**Comment by guwac** [comment]
@trensen: This `(source)` annotation was exactly the starting point of this discussion (as explained in  https://github.com/TUDelft-IN4303/assignments/blob/master/milestone3-codegen/questions.md).

**Comment by mvandertuin** [comment]
Manually desugaring by using the <desugar-all> strategy fixed the issue.
